# ETL2/config.yml

data:
  input_path: "01_data/input/measurements.csv"
  working_dir: "01_data/working"
  output_path: "01_data/output/ngsiv2_output.json"

transform_duckdb:
  query_paths:
    - "04_queries/01_validate_source.sql"
    - "04_queries/02_structure_to_ngsi.sql"
  ngsi_entity_type: "AirQualityMeasurement"

transform_jinja:
  template_path: "03_templates/to_ngsiv2.json.j2"
  output_filename: "ngsiv2_interim.json"