# ETL3/config.yml
data:
  input_path: "01_data/input/device_logs.json"
  working_dir: "01_data/working"
  output_path: "01_data/output/ngsiv2_from_json.json"

validation:
  input_schema_path: "02_metadata/input_schema.json"
  output_schema_path: "02_metadata/output_schema.json"

transform_duckdb:
  query_paths:
    - "04_queries/transform_device_logs.sql"
  ngsi_entity_type: "DeviceMeasurement"

transform_jinja:
  template_path: "03_templates/to_ngsiv2_entity.json.j2"
  output_filename: "ngsiv2_interim.json"