# ETL1/config.yml

data:
  input_path: "01_data/input/source_data.csv"
  working_dir: "01_data/working"
  output_path: "01_data/output/final_data.parquet"

transform_duckdb:
  query_path: "04_queries/add_timestamp.sql"
  new_column_name: "processed_at"

transform_jinja:
  template_path: "03_templates/report.html.j2"
  output_filename: "summary_report.html"
  report_title: "日次処理サマリー"