version: '3'
services:
  atlas:
    image: sburn/apache-atlas
    hostname: atlas
    container_name: atlas
    ports:
      - "21000:21000"
    networks:
      - atlas-network
    environment:
      MANAGE_LOCAL_HBASE: "true"
      MANAGE_LOCAL_SOLR: "false"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: nc -z localhost 21000 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - atlas-network
    healthcheck:
      test: echo ruok | nc localhost 2181
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  atlas-network:
    driver: bridge
