# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-09-27T08:22:13+00:00

from __future__ import annotations

from pydantic import BaseModel


class Inputschema(BaseModel):
    name: str
    address: str
    capacity: float
    latitude: float
    longitude: float
