# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-09-27T08:17:03+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel


class EntityType(StrEnum):
    Place = 'Place'


class Type(StrEnum):
    Text = 'Text'


class Name(BaseModel):
    value: str
    type: Type


class Address(BaseModel):
    value: str
    type: Type


class Type2(StrEnum):
    Number = 'Number'


class Capacity(BaseModel):
    value: float
    type: Type2


class Latitude(BaseModel):
    value: float
    type: Type2


class Longitude(BaseModel):
    value: float
    type: Type2


class Outputschema(BaseModel):
    entityId: str
    entityType: EntityType
    name: Name
    address: Address
    capacity: Capacity
    latitude: Latitude
    longitude: Longitude
